#!/bin/sh

rm -rf release

script/build_artifact x86_64-unknown-linux-gnu
script/build_artifact x86_64-unknown-linux-musl
script/build_artifact aarch64-unknown-linux-gnu
script/build_artifact aarch64-unknown-linux-musl
