#!/usr/bin/env ruby
# frozen_string_literal: true

VERSION=ARGV[0]

File.write(
  "Cargo.toml",
  File.read("Cargo.toml").sub(/^version = ".*"$/, %(version = "#{VERSION}"))
)

File.write(
  "install.sh",
  File.read("install.sh").sub(/^LAST_RELEASE=".*"$/, %(LAST_RELEASE="#{VERSION}"))
)
